{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-additional-test-output",
    "version": "31.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.2.2.jar",
          "url": "android-test-plugin-host-additional-test-output-31.2.2.jar",
          "size": 16345,
          "sha512": "1153eff8706168693ab238948a8fd106fcf328b8d27c8fd5ece43cae2faf3869de1bcf044c5180ef79eee160d50453f46eb7acbf61df041ef8eb4ba7d0227b4a",
          "sha256": "9c7bfbd275b13ae8190f5cc5fe5aba568e53063e10e754f5e233ad12bfbb6624",
          "sha1": "7cc9d629c341fc208d4754474a5d8e19177e6c3d",
          "md5": "60cf4db6f0f48b6f1eb8d422fa7a0ca5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.8-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.2.2.jar",
          "url": "android-test-plugin-host-additional-test-output-31.2.2.jar",
          "size": 16345,
          "sha512": "1153eff8706168693ab238948a8fd106fcf328b8d27c8fd5ece43cae2faf3869de1bcf044c5180ef79eee160d50453f46eb7acbf61df041ef8eb4ba7d0227b4a",
          "sha256": "9c7bfbd275b13ae8190f5cc5fe5aba568e53063e10e754f5e233ad12bfbb6624",
          "sha1": "7cc9d629c341fc208d4754474a5d8e19177e6c3d",
          "md5": "60cf4db6f0f48b6f1eb8d422fa7a0ca5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.2.2-javadoc.jar",
          "url": "android-test-plugin-host-additional-test-output-31.2.2-javadoc.jar",
          "size": 261,
          "sha512": "87506234bc4f28efe96eb54c2b4e0ca6cb3fb9f71a8599542ce7047023ba2da69c4657a2fed8fb4ef4add74d4295bbc898190a1bf4319220b1c10c9d88aaed49",
          "sha256": "2280ccd325d6c4523c8c39e9d6643f7a4b56badd287a82b169275c74acd7e398",
          "sha1": "87f71928fc92df3f93b2d72416e2af18ea3a84cd",
          "md5": "8dc1f01b079c027c58ce57bf854234fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-additional-test-output-31.2.2-sources.jar",
          "url": "android-test-plugin-host-additional-test-output-31.2.2-sources.jar",
          "size": 5392,
          "sha512": "72159a9a2ad9a96197a996bc95b020f1b665c34641bd166638330f0d7b378dd49db3dd1d5ce4bbb9f6171578b74ba4b0e16d9995c3e0afec79b3c96f9a64275d",
          "sha256": "d8a8a3d444ff46af713fbd6225c5ed66db360206d7c2fe06219249b150edcb1a",
          "sha1": "4baaa278436842bd468b2765434af12edcf64e65",
          "md5": "80659dc55cde9e8df73fb358162d0666"
        }
      ]
    }
  ]
}
