{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage",
    "version": "31.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.2.2.jar",
          "url": "android-test-plugin-host-coverage-31.2.2.jar",
          "size": 17363,
          "sha512": "0d50da73acb7187b0536ce0b40b7f65c346734124ae3dde4d9c273774e4b7eaa9ea9020eebe63acd94296efa40a00ce46eeb3072ced4867adb3e90c55f0d9b4d",
          "sha256": "04e871a4d16427bf4f6c01e32da6302addcb50cfd6f490ca2bf69e797d8d413e",
          "sha1": "1d3d89369c4bba7f3bc797a853f20ec15d22dc2c",
          "md5": "ae5139c8f5f2826bfa880ae563fe27db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.8-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.2.2.jar",
          "url": "android-test-plugin-host-coverage-31.2.2.jar",
          "size": 17363,
          "sha512": "0d50da73acb7187b0536ce0b40b7f65c346734124ae3dde4d9c273774e4b7eaa9ea9020eebe63acd94296efa40a00ce46eeb3072ced4867adb3e90c55f0d9b4d",
          "sha256": "04e871a4d16427bf4f6c01e32da6302addcb50cfd6f490ca2bf69e797d8d413e",
          "sha1": "1d3d89369c4bba7f3bc797a853f20ec15d22dc2c",
          "md5": "ae5139c8f5f2826bfa880ae563fe27db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.2.2-javadoc.jar",
          "url": "android-test-plugin-host-coverage-31.2.2-javadoc.jar",
          "size": 261,
          "sha512": "6bae3568b8d2d9677e9a6585f50b767d5dbf39ff74567fef36992bf616977cdbf85f97e2cf2ceefd362c3898ff5b78c1c35660327740f0c62d4ef0d965998228",
          "sha256": "0fad80cb36e8ef8ca1e39725a4b9867070a79d115a39635f9ed417b5417a34bb",
          "sha1": "c9a36d4abe9647f6d7ea78c76b0401061d58adff",
          "md5": "7037f0c829065c4e67b194dc413f96e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.2.2-sources.jar",
          "url": "android-test-plugin-host-coverage-31.2.2-sources.jar",
          "size": 4847,
          "sha512": "42b041dbce1730f8768a43d588d617039b6b80809b7f03c3c0ec53c15c7b92c1dc19b508a790feec807346c64b8dcf4b52a1d584c4e70b44bde5fdd62f4da941",
          "sha256": "f259119514dc17b832fc99ac141a4e1412a8653be256c32f814aa5cca9e94468",
          "sha1": "b552777562b48e9667243a6efa03a86a98f16276",
          "md5": "80a29887cdbd2040173b21a851ae1daf"
        }
      ]
    }
  ]
}
