{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-device-info",
    "version": "31.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.2.2.jar",
          "url": "android-test-plugin-host-device-info-31.2.2.jar",
          "size": 10338,
          "sha512": "6a350a5174de577ef660d37db9fd00029aceac06213d8476c03b7cec1ed11ef4fa8d5d8bdaeccd420c5fa8904a6a36e0fafd68d4639a12d71525138830a4256e",
          "sha256": "a504cb12ca8839c3c29152043a2003977595d3e15eb9a9932dd4c0eba5f74f90",
          "sha1": "890df92eca65af8d06d0e20c8f4e58375f7fbf32",
          "md5": "3c3b99fce5a2f6c78a4e51ffa8853016"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-device-info-proto",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.8-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.2.2.jar",
          "url": "android-test-plugin-host-device-info-31.2.2.jar",
          "size": 10338,
          "sha512": "6a350a5174de577ef660d37db9fd00029aceac06213d8476c03b7cec1ed11ef4fa8d5d8bdaeccd420c5fa8904a6a36e0fafd68d4639a12d71525138830a4256e",
          "sha256": "a504cb12ca8839c3c29152043a2003977595d3e15eb9a9932dd4c0eba5f74f90",
          "sha1": "890df92eca65af8d06d0e20c8f4e58375f7fbf32",
          "md5": "3c3b99fce5a2f6c78a4e51ffa8853016"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.2.2-javadoc.jar",
          "url": "android-test-plugin-host-device-info-31.2.2-javadoc.jar",
          "size": 261,
          "sha512": "6bae3568b8d2d9677e9a6585f50b767d5dbf39ff74567fef36992bf616977cdbf85f97e2cf2ceefd362c3898ff5b78c1c35660327740f0c62d4ef0d965998228",
          "sha256": "0fad80cb36e8ef8ca1e39725a4b9867070a79d115a39635f9ed417b5417a34bb",
          "sha1": "c9a36d4abe9647f6d7ea78c76b0401061d58adff",
          "md5": "7037f0c829065c4e67b194dc413f96e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-31.2.2-sources.jar",
          "url": "android-test-plugin-host-device-info-31.2.2-sources.jar",
          "size": 4354,
          "sha512": "4c5cd07d3702ce972022940a2ab3d5dbf457669b7cad8cde7b45ebfcb14c2e5b5c3dfa9fbfb08e98df0688a54d0e1e9ee6182fe5cf6e9103fd679d8b89249ebe",
          "sha256": "f314acc111a1a85fffcf924bea87185f6d29076086130d5be3e669f3a3854e16",
          "sha1": "9182590cf3463ffa2b82b21f5250f1e102800dfe",
          "md5": "d15bd28791f364a36a4b50a6c04f9557"
        }
      ]
    }
  ]
}
